"""Add profile_image column

Revision ID: 04e8dccd3d56
Revises: f707d9d287d5
Create Date: 2025-10-25 08:07:42.652023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e8dccd3d56'
down_revision = 'f707d9d287d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.Text(), nullable=True))
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
