"""add name and company to centers

Revision ID: e31e79c3ede0
Revises: b269d29f9a55
Create Date: 2025-10-26 11:41:54.139070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31e79c3ede0'
down_revision = 'b269d29f9a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.drop_column('company')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
