"""updating users model

Revision ID: f707d9d287d5
Revises: 4829975b79b9
Create Date: 2025-10-25 07:42:50.438157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f707d9d287d5'
down_revision = '4829975b79b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=512), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.TEXT(), nullable=True))
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###
